### ISSUE TITLE
Login pagina

### ISSUE THREAD

**Issue by Matthiee** [yannor/WindowsProjectHogeschool#10]
Login pagina maken voor de admin?

Hier is hoe ik denk het te doen:
Als hij ingelogd is komt er met een visual state **_(IsLoggedIn)_** op elke pagina ene knop "Bewerk" bij.
hierin kan hij dan de pagina aanpassen door op de knop te duwen gaat hij met een andere visual state **_InEditMode_** de pagina met bewerkbare velden zien.

**Comment by yannor** [comment]
Zou je dan in dezelfde pagina werken met die visual states?
Of zou je gewoon if(loggedIn) een andere pagina loaden?

**Comment by Matthiee** [comment]
Zelfde is het makkelijkste denk ik

**Comment by yannor** [comment]
Ok. Dan doen we het zo.
