### ISSUE TITLE
Backend

### ISSUE THREAD

**Issue by Matthiee** [yannor/WindowsProjectHogeschool#11]
Deze heeft 2 tabellen nodig:

1. Richting
2. Admin

Zijn er nog nodig?

**Comment by yannor** [comment]
... En admin is dan enkel een boolean?
Zou je het niet user noemen, en die dan een boolean admin geven?
Want waarschijnlijk heeft die een email en wachtwoord nodig.

**Comment by Matthiee** [comment]
User is ook goed ook al gaan we er geen echte users insteken maar alleen admins. 
En ja email of username en ww

**Comment by yannor** [comment]
En wat als (ok misschien is er niet zoveel tijd meer) we er een knop insteken waarmee mensen kunnen zeggen van ik heb interesse. Ze krijgen dan een menu met email adres (nieuwe user) en de lijst van deze gebruikers kan de admin zien. Zo zien ze wie er interesse heeft?

**Comment by yannor** [comment]
En dan mensen met interesse krijgen een nieuwsbrief ofzo? idk

**Comment by yannor** [comment]
Ok die nieuwsbrief is wat ver gezocht.
Maar moeten we in onze backend geen evenement hebben? Zodat ze opendeurdagen enz de datums kunnen aanpassen. check #12

**Comment by Matthiee** [comment]
Nieuwsbrief is idd wa ver gezocht & ja een evenement is ook goed voor mij

**Comment by yannor** [comment]
Misschien ipv evenement campus? Deze heeft dan de tekst van de mainpage en deze bevat dan een lijst van evenementen
