### ISSUE TITLE
Hoofdpagina

### ISSUE THREAD

**Issue by yannor** [yannor/WindowsProjectHogeschool#12]
In de hoofdpagina zit nu een knop waarmee je de opendeurdag rechtstreeks aan je agenda kunt toevoegen. Deze staat hardcoded. 
Moeten we dan in backend geen klasse hebben met evenementen waarin ze evenementen kunnen toevoegen (met datums) die mensen dan in hun agenda kunnen zetten?
Ook kunnen we enkele dagen ervoor een notification sturen?

In onze hoofdpagina zouden we ook zo nieuws doen? Enig idee hoe we deze fotos gaan aanpassen?

@DriesWillems Kan jij een mockup maken van onze hoodpagina waar in die map zit, een nieuwsding, wat tekst, een kaderke met het adres enz en eventueel data van onze evenementen.

Graag mening over dit van jullie? @DriesWillems @Matthiee

**Comment by ghost** [comment]
Zie mail voor mock up

**Comment by yannor** [comment]
Ok. Misschien kunnen we dat nieuws weglaten? Kwestie van tijd.
Evenementen vind ik goed al zou ik ze wel naast mekaar zetten.
En ja bij evenementen zou ik bij alles de mogelijkheid geven om aan de kalender toe te voegen.
Natuurlijk moet het daar dan mogelijk zijn om nieuwe bij te voegen...
